#ifndef STATUS_H
#define STATUS_H

#define HAL_OFFSET 100
enum ReturnStatus
{
  RT_OK=0,
  RT_I2C_READ_FAILED=1,
  RT_I2C_WRITE_FAILED=2,
  RT_SPI_READ_FAILED=3,
  RT_SPI_WRITE_FAILED=4,
  RT_OUT_OF_MEMORY=5,
  RT_LORA_CRC_ERR=6,
  RT_CBOR_ERR=7,
  RT_TIMEOUT=8,
  RT_ERR_DISPLAY_INIT=9,
  RT_GPIO_SETUP_ERR=10,
  RT_SPI_INIT_FAILED=11,
  RT_SWITCH_LORA_FAILED=12,
  RT_HEADER_WITHOUT_CRC=13,
};

#endif
